name: fitness_app
description: A pixel-perfect fitness app with dark theme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  syncfusion_flutter_gauges: ^25.1.35
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
